data_root: ${oc.env:DATA_ROOT}
eval_every_n_epochs: 1
per_epoch_evaluations:
  {
    "tinyface":
      {
        "path": "facerec_val/tinyface_aligned_pad_0.1",
        "evaluation_type": "tinyface",
        "color_space": "RGB",
        "batch_size": 32,
        "num_workers": 4,
      },
  }
